services:
  postgres_test:
    image: postgres:15
    container_name: postgres_test_db
    restart: always
    environment:
      POSTGRES_USER: planuser
      POSTGRES_PASSWORD: planpassword
      POSTGRES_DB: plandb
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
