
services:
  pg:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: general
      POSTGRES_PASSWORD: sexpasssecret
      POSTGRES_DB: plandbmain
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
