"""связь Projects, PhotoProjects

Revision ID: 2b4276deb58c
Revises: 171c168f08ca
Create Date: 2025-08-20 10:57:29.053955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b4276deb58c"
down_revision: Union[str, Sequence[str], None] = "171c168f08ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photo_projects",
        sa.Column("link", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "photo_projects", sa.Column("project_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_photo_projects_project_id_projects"),
        "photo_projects",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("projects", sa.Column("comments", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f("fk_projects_user_id_users"),
        "projects",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_user_id_users"), "projects", type_="foreignkey"
    )
    op.drop_column("projects", "user_id")
    op.drop_column("projects", "comments")
    op.drop_constraint(
        op.f("fk_photo_projects_project_id_projects"),
        "photo_projects",
        type_="foreignkey",
    )
    op.drop_column("photo_projects", "project_id")
    op.drop_column("photo_projects", "link")
    # ### end Alembic commands ###
