"""связь Projects, PhotoProjects refactor

Revision ID: 654947073f31
Revises: 2b4276deb58c
Create Date: 2025-08-20 11:31:26.366596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "654947073f31"
down_revision: Union[str, Sequence[str], None] = "2b4276deb58c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
